version: "3.8"

services:
  smtp-statement:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - api/.env
    volumes:
      - ./api:/app
    restart: unless-stopped
    networks:
      - backend
networks:
  backend:
    name: backend
